# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
