# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_website', '0002_auto_20160820_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L'), ('600L', '600L')], max_length=1)),
            ],
        ),
    ]
