# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_website', '0003_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(default='ss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimony',
            name='level',
            field=models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L'), ('600L', '600L')], max_length=4),
        ),
    ]
