# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_website', '0004_auto_20160820_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_description', models.CharField(max_length=100, verbose_name='Image Description')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
