# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_website', '0006_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='')),
                ('content', models.TextField()),
                ('position', models.CharField(max_length=30)),
            ],
        ),
    ]
